### ISSUE TITLE
Discovery: Rudimentary Personas & Scenarios

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/vets-json-schema#363]
## User Story or Problem Statement
As a UX Designer, I need to create rudimentary personas and scenarios so I can share these artifacts with my team prior to the feature scoping activity.

## Tasks
- [ ] Meet with designers to discuss synthesized findings and determine intended persona archetypes (1 hour)
- [ ] Create rudimentary persona documents (1 hour)

## Acceptance Criteria
- [ ] Rough outline of personas uploaded to GH
- [ ] Rough list of scenarios uploaded to GH

## Next Steps
- Create higher fidelity personas
- Turn scenarios into customer journeys (and possibly service blueprints)

## Blockers
- N/A

**Comment by rileyorr** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #4298](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4298) via [**ZenHub**](https://www.zenhub.com/)
